### ISSUE TITLE
nginx update

### ISSUE THREAD

**Issue by thetux07** [jhampson-dbre/nginx-proxy-waf#7]
hello,
can you update nginx version ?
thank you

**Comment by jhampson-dbre** [comment]
I've been looking at doing this for a little while now. I'm considering switching to the package from nginx.org instead of the one that ships with Alpine OS because it provides better support for adding the modsecurity module. The only drawback of this is that nginx.org version only provides x86_64 (intel 64-bit) and aarch64 (arm 64-bit). Can you check if your CPU is 64-bit compatible? You can check at https://my.home-assistant.io/redirect/info/ or under Configuration>Setting>Info.

![image](https://user-images.githubusercontent.com/27974655/152900447-f4a62339-213b-457e-940b-765b301e2db9.png)

If yours is compatible, I'll go ahead and make the switch and work on getting the new version published.

**Comment by thetux07** [comment]
hello thank you yes i have a Intel Nuc

**Comment by jhampson-dbre** [comment]
I'll have to look into it, but it's possible that flv-http-module could be possible to add. Can you explain what the flv-http-module is used for?

**Comment by jhampson-dbre** [comment]
Nginx is updated to latest stable version 1.20.2 in version 4.0.0 and higher of the add on. If you have more details about the flv-http-module is used for, we can make a separate issue for that.
